version: "3.1"

services:
  drupal:
   image: drupal:8.2
   ports:
    - '80:80'
   volumes:
     - drupal_modules:/var/www/html/modules
     - drupal_profiles:/var/www/html/profiles
     - drupal_themes:/var/www/html/themes
     - drupal_sites:/var/www/html/sites
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD_FILE: "/run/secrets/psql_pass"
    secrets:
      - psql_pass
    volumes:
     - "drupal_data:/var/lib/postgresql/data"

volumes:
  drupal_data:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:

secrets:
  psql_pass:
   external: true
