version: "3"

services:
  drupal:
   image: drupal:8-apache
   ports:
    - '8008:80'
   volumes:
     - /var/www/html/modules
     - /var/www/html/profiles
     - /var/www/html/themes
     - /var/www/html/sites
   restart: always
  postgres:
    image: postgres:9.6.2
    environment:
     POSTGRES_PASSWORD: "set4now"
     POSTGRES_USERNAME: "postgres"
    restart: always
