version: "3"

services:
  drupal:
   image: drupal:8-apache
   ports:
    - '8008:80'
   volumes:
     - drupal_modules:/var/www/html/modules
     - drupal_profiles:/var/www/html/profiles
     - drupal_themes:/var/www/html/themes
     - drupal_sites:/var/www/html/sites
   restart: always
  postgres:
    image: postgres:9.6.2
    environment:
     POSTGRES_PASSWORD: "set4now"
     POSTGRES_USERNAME: "postgres"
    restart: always

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
