version: "3.1"

services:

  drupal:
    image: drupal:8.2
    deploy:
#      replicas: 2
      restart_policy: 
        condition: on-failure
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    ports:
      - "80:80"
    networks:
      - my_stack_drupal

  postgres:
    image: postgres:9.6
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - psql_pass
      - psql_user
    environment:
      POSTGRES_USER_FILE: "/run/secrets/psql_user"
      POSTGRES_PASSWORD_FILE: "/run/secrets/psql_pass"
    networks:
      - my_stack_drupal

secrets:
  psql_pass:
    external: true
  psql_user: 
    file: ./psql_user.txt

volumes:
  db_data:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:


networks:
  my_stack_drupal:
